### ISSUE TITLE
Use `standard` storageClass as default

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [sitewhere/sitewhere-k8s#26]
- [x] Favor `standard` storage class instead of `rook-ceph-block` as the default storage class of `PersistenVolumenClaim`. 
- [x] Also, provide `values-rook-ceph.yaml` in order to be able to start SiteWhere with `rook-ceph-block` storageClass. 
- [x] Update documentation.

**Comment by GanKanTechnology** [comment]
Hi @jorgevillaverde-sitewhere  
Glad to see that you've updated it. I've just tested this new chart , for now it can run and all demo data in the sitewhere-tenant can be displayed by admin-ui now. Congratulations ! I'm going to do more test.   Hope it will perform stable. Thank  you both~

By the way,I have a small question: Is there any special reason to use `standard` storageClass ?  I create it manually like below:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: standard
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  clusterNamespace: rook-ceph
  fstype: xfs
```
