### ISSUE TITLE
Allow using external Kafka servers

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [sitewhere/sitewhere-k8s#39]
Provide the necessary configuration to allow the use of an external Kafka/Zookeeper infrastructure.

- [x] Define the parameters that the helm chart will use for the external Kafka/Zookeeper infrastructure.
- [x] Implement a template function to resolve Kafka and Zookeeper environment variable to microservices.
- [x] Update the documentation.

**Comment by jorgevillaverde-sitewhere** [comment]
Define new parameters for Kafka and Zookeer hostname and ports

```yaml
sitewhere-infra-core:
  kafka:
    enabled: true
    kafka_host: ""
    kafka_port: ""
    zookeeper_host: ""
    zookeeper_port: ""
 ```

Use the following command for using external Kafka and Zookeeper infrastructure:

```console
helm install --name sitewhere \
  --set sitewhere-infra-core.kafka.enabled=false \
  --set sitewhere-infra-core.kafka.zookeeper_host=<zk-locahost> \
  --set sitewhere-infra-core.kafka.zookeeper_port=<zk-port> \
  --set sitewhere-infra-core.kafka.kafka_host=<kafka-locahost> \
  --set sitewhere-infra-core.kafka.kafka_port=<kafka-port> \
  sitewhere/sitewhere
```
