### ISSUE TITLE
Avoid sidecar injection to infra-core components.

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [sitewhere/sitewhere-k8s#49]
Add `podAnnotations` to infra-core components to avoid Istio sidecar injection.

```yaml
  template:
    metadata:
      podAnnotations:
        sidecar.istio.io/inject: "false"
```
