### ISSUE TITLE
Avoid sidecar injection to infra-database components.

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [sitewhere/sitewhere-k8s#50]
Add `podAnnotations` to infra-database components to avoid Istio sidecar injection.
```yaml
  template:
    metadata:
      podAnnotations:
        sidecar.istio.io/inject: "false"
```
