### ISSUE TITLE
[QUESTION] Running on bare-metal cluster & Metal-LB

### ISSUE THREAD

**Issue by Sudokamikaze** [sitewhere/sitewhere-k8s#93]
Hello fellow developers, everything works fine, except one thing.
I'm using Metal-LB v0.8.1. Configuration map of metal-lb:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      -my_external_ip/32
```

As you've noticed, it's 32 mask up here, so I had to use shared IP annotation, here's the way I'm using it with Istio & Sitewhere

Istio:
```wget https://github.com/istio/istio/releases/download/1.2.2/istio-1.2.2-linux.tar.gz
tar -xvf istio-1.2.2-linux.tar.gz
cd istio-1.2.2
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f install/kubernetes/istio-demo.yaml
kubectl label namespace default istio-injection=enabled
kubectl annotate svc istio-ingressgateway metallb.universe.tf/allow-shared-ip=sitewhere-mosquitto --namespace istio-system```

Sitewhere:
```## Deploy Sitewhere
`helm install --name sitewhere \
--set sitewhere-infra-core.cp-kafka.persistence.storageClass=hostpath \
--set sitewhere-infra-core.cp-zookeeper.persistence.dataLogDirStorageClass=hostpath \
--set sitewhere-infra-database.mongodb.persistence.storageClass=hostpath \
--set sitewhere-infra-database.cassandra.persistence.storageClass=hostpath \
--set sitewhere-infra-database.influxdb.persistence.storageClass=hostpath \
sitewhere/sitewhere && kubectl annotate svc sitewhere-mosquitto-svc metallb.universe.tf/allow-shared-ip=sitewhere-mosquitto```

By NMAPing my external IP, I see that ports are opened, but when I do something with MQTT, there's no logs that something happened at sitewhere-event-sources

Should I buy another IP address or what might caused that behavior? Thanks in advance
